DjangoAGH/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('score.urls'))
]

score/urls.py
from django.urls import path

from . import views

app_name = 'score'
urlpatterns = [
    path('', views.index, name='index'),
    path('subjects/', views.SubjectListView.as_view(), name='subjects'),
    path('subjects/new/', views.SubjectFormView.as_view(), name='new_subject'),
    path('subjects/<int:pk>/', views.SubjectDetailView.as_view(), name='subject'),
    path('fields/', views.FieldListView.as_view(), name='fields'),
    path('fields/new/', views.FieldFormView.as_view(), name='new_field'),
    path('fields/<int:pk>/', views.FieldDetailView.as_view(), name='field')
]

score/models.py
from django.db import models

# Create your models here.


class Subject(models.Model):
    name = models.CharField(max_length=30)
    max_points = models.FloatField(null=True)
    my_points = models.FloatField(null=True)
    extended = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def percent(self):
        return self.my_points / self.max_points


class Field(models.Model):
    name = models.CharField(max_length=20)
    r1 = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='r1')
    r2 = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='r2')
    p = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='basic')

    def __str__(self):
        return self.name

    def get_g(self):
        output = []
        for item in (self.r1.percent(), self.r2.percent()):
            if item < 30:
                output.append(item)
            elif item <= 80:
                output.append(item + 2 * (item - 30))
            else:
                output.append(item + 100)
        g = 0.75 * output[0] * 0.25 * output[1]
        return g

    def get_m(self):
        return 2 * self.p.percent()

    def get_w(self):
        return 4 * self.get_g() + self.get_m()

score/forms.py
from django import forms
from .models import Subject


class SubjectForm(forms.Form):
    name = forms.CharField(label='Name', max_length=30)
    max_pkt = forms.FloatField(label='Max pkt')
    your_pkt = forms.FloatField(label='Your pkt')
    extended = forms.BooleanField(initial=True)


class FieldForm(forms.Form):
    name = forms.CharField(label='Name', max_length=30)
    r1 = forms.ModelChoiceField(queryset=Subject.objects.all(), empty_label='[Extended Level]')
    r2 = forms.ModelChoiceField(empty_label='[Second Extended Subject]', queryset=Subject.objects.all())
    p = forms.ModelChoiceField(queryset=Subject.objects.all(), empty_label='[Basic Level]')

score/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy

from .forms import SubjectForm, FieldForm
from .models import Subject, Field

from django.views import generic


# Create your views here.
def index(request):
    return render(request, 'score/index.html', {
        'index_active': True
    })


class SubjectListView(generic.ListView):
    template_name = 'score/list.html'
    context_object_name = 'lst'
    extra_context = {
        'add_url': reverse_lazy("score:new_subject"),
        'class_name': 'subject',
        'subjects_active': True
    }

    def get_queryset(self):
        return Subject.objects.all()


class FieldListView(generic.ListView):
    template_name = 'score/list.html'
    context_object_name = 'lst'
    extra_context = {
        'add_url': reverse_lazy("score:new_field"),
        'class_name': 'field',
        'fields_active': True
    }

    def get_queryset(self):
        return Field.objects.all()


class SubjectDetailView(generic.DetailView):
    model = Subject
    template_name = 'score/detail.html'
    context_object_name = 'model'
    extra_context = {
        'subjects_active': True
    }


class FieldDetailView(generic.DetailView):
    model = Field
    template_name = 'score/detail.html'
    context_object_name = 'model'
    extra_context = {
        'fields_active'
    }


class SubjectFormView(generic.edit.FormView):
    template_name = 'score/new.html'
    form_class = SubjectForm
    success_url = reverse_lazy('score:subjects')
    extra_context = {
        'form_name': 'New Subject',
        'subjects_active': True,
        'action': reverse_lazy('score:new_field')
    }

    def form_valid(self, form):
        s = Subject(name=form.cleaned_data['name'])
        s.max_points = form.cleaned_data['max_pkt']
        s.my_points = form.cleaned_data['your_pkt']
        s.save()
        return super().form_valid(form)


class FieldFormView(generic.edit.FormView):
    template_name = 'score/new.html'
    form_class = FieldForm
    success_url = reverse_lazy('score:fields')
    extra_context = {
        'form_name': 'New Field',
        'field_active': True,
        'action': reverse_lazy('score:new_field')
    }

    def form_valid(self, form):
        f = Field(name=form.cleaned_data['name'])
        f.r1 = form.cleaned_data['r1']
        f.r2 = form.cleaned_data['r2']
        f.p = form.cleaned_data['p']
        f.save()

        return super().form_valid(form)

templates/score/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static 'score/bootstrap.min.css' %}"
          rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
          crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link {% if index_active %}active{% endif %}" aria-current="page" href="{% url 'score:index' %}">Home</a>
                    </li>

                    <li class="nav-item">
                      <a class="nav-link {% if subjects_active %}active{% endif %}" href="{% url 'score:subjects' %}">Subjects</a>
                    </li>

                    <li class="nav-item">
                      <a class="nav-link {% if fields_active %}active{% endif %}" href="{% url 'score:fields' %}">Fields</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link {% if points_active %}active{% endif %}" href="#">Calculate Points</a>
                    </li>

                  </ul>
                  <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                  </form>
                </div>
              </div>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col d-flex justify-content-center">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
<div class="row fixed-bottom modal-footer d-flex justify-content-center">
        <h6 class="text-center">@ Mateusz Wlekliński 2021</h6>
</div>

</body>
</html>

templates/score/detail.html
{% extends 'score/base.html' %}

{% block content %}
<h4>{{ model }}</h4>
{% endblock %}

templates/score/index.html
{% extends 'score/base.html' %}
{% load static %}

{% block title %}
Index
{% endblock %}

{% block content %}
    <div class="card text-center">
        <div class="card-header">
            <h4>Hello World</h4>
        </div>
        <div class="card-body">
            <img src="{% static 'score/matrix.jpeg' %}" class="card-img-top">
            <p class="card-text">Welcome to our Page!</p>
        </div>
        <div class="card-footer">
            <a href="#" class="btn btn-outline-success">Get Started</a>
        </div>
    </div>
{% endblock %}

templates/score/list.html
{% extends 'score/base.html' %}

{% block content %}

    <div class="card text-center w-25">
        <div class="card-header">
            <h4>{{ class_name | title }}</h4>
        </div>
        {% if lst %}
            <div class="card-body">
                <ul class="list-group">
                {% for item in lst %}
                    <li class="list-group-item list-group-item-dark">
                        <a class="btn btn-outline-info"
                                {% if class_name == 'subject' %}
                                    href="{% url 'score:subject' item.id %}"
                                {% else %}
                                    href="{% url 'score:field' item.id %}"
                                {% endif %}>
                            {{ item | title }}
                        </a>
                    </li>
                {% endfor %}
                </ul>
            </div>
        {% endif %}
        <div class="card-footer">
            <a href="{{ add_url }}" class="btn btn-outline-success">Add New</a>
        </div>
    </div>




{% endblock %}

templates/score/new.html
{% extends 'score/base.html' %}
{% load bootstrap5 %}

{% block title %}
    Form
{% endblock %}

{% block content %}
{% if error_message %}
    <p>
        <strong>
            {{ error_message }}
        </strong>
    </p>
{% endif %}
    <div class="card">
        <div class="card-footer text-center">
            {{ form_name }}
        </div>
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Add</button>
                {% endbuttons %}
            </form>
        </div>
    </div>



{% endblock %}